#!/usr/bin/env bash
# Install Nginx package
apt-get update
apt-get install -y nginx
HOSTNAME=$(hostname)
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /var/www/html;
    index index.html index.htm;

    location / {
        echo 'Hello World!';
        add_header X-Served-By $HOSTNAME;
    }
}" > /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
nginx -t
systemctl reload nginx

