#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server
install_and_configure_haproxy() {
	sudo apt-get -y update
	sudo apt-get -y upgrade
	sudo apt-get -y install software-properties-common
    	sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
    	sudo apt-get -y update
	sudo apt-get -y install haproxy
	sudo echo "ENABLED=1" > /etc/default/haproxy

	sudo cp /etc/haproxy/haproxy.cfg{,.orig}

	sudo cat <<EOL >> /etc/haproxy/haproxy.cfg
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 287018-web-01 100.27.11.52:80 check
    server 287018-web-02 54.237.72.95:80 check
EOL

	sudo service haproxy restart
}
install_and_configure_haproxy
