#!/usr/bin/env bash
# install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update
sudo apt-get -y install haproxy
echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg{,.orig}
sudo tee -a /etc/haproxy/haproxy.cfg <<EOL
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 287018-01 100.25.198.81:80 check
    server 287018-02 34.202.157.80:80 check
EOL
sudo systemctl restart haproxy

