#!/usr/bin/env bash
# nstall and configure HAproxy on your lb-01 server
sudo apt-get update
sudo apt-get install -y haproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend web
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 287018-web-01 100.25.198.81:80 check
    server 287018-web-02 34.202.157.80:80 check
EOF
sudo systemctl enable haproxy
sudo systemctl restart haproxy
sudo systemctl status haproxy
