#!/usr/bin/env bash
# This script Creates the file /var/run/myscript.pid containing its PID
f="/var/run/myscript.pid"
echo $$ > "$f"
trap 'echo "I hate the kill command"'; 'rm "$f"; exit'; SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm "$f"; exit' SIGQUIT
while true;
do
  echo "To infinity and beyond"
  sleep 1
done

