#!/usr/bin/env bash
# This script Creates the file /var/run/myscript.pid containing its PID
f="/var/run/myscript.pid"
echo $$ > "$f"
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm "$f"; exit';exit 0; SIGQUIT SIGTERM
while true;
do
  echo "To infinity and beyond"
  sleep 2
done

