#!/usr/bin/env bash
f="/var/run/myscript.pid"
echo $$ > "$f"
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm "$f"; exit' SIGQUIT SIGTERM
while true;
do
  echo "To infinity and beyond"
  sleep 2
done

