#!/usr/bin/env bash
# This Bash script that displays numbers from 1 to 100
n=1
while ((n <= 100))
do
        if ((n % 3 == 0)); then
                echo "Fizz"
        elif ((n % 5 == 0)); then
                echo "Buzz"
	elif ((n % 5 == 0 && n % 3 == 0)); then
		echo "FizzBuzz"
        else
                echo $n
        fi
        ((n+=1))
done
