#!/usr/bin/env bash
# This is Bash script that displays the time for 12 hours and 59 minutes
h=0
while ((h < 12))
do
	echo "Hour: $h"
	m=1
	while ((m < 60))
	do
		echo $m
		((m+=1))
	done
	((h+= 1))
done	

