#!/usr/bin/env bash
# SH configuration file for the local SSH client
Host *
    HostName 100.25.198.81
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
    PubkeyAuthentication yes
